Blog1.0/Controllers/ArticleController.cs
using Blog1._0.Service;
using System;
using System.Linq;
using System.Web.Mvc;
using Until;

namespace Blog1._0.Controllers
{
    /// <summary>
    /// 【博客】控制器
    /// </summary>
    public class ArticleController : Controller
    {
        ArticleService article = new ArticleService();
        /// <summary>
        /// 文章列表视图
        /// </summary>
        /// <returns></returns>
        public ActionResult Index(string DPOR369E0zc)
        {
            var ArticleID = DPOR369E0zc == null ? 0 : Convert.ToInt32(Des.DesDecrypt("guo", DPOR369E0zc));
            Admin_ArticleService classService = new Admin_ArticleService();
            LinksService link = new LinksService();
            WebSiteInfo model = new WebSiteInfo();
            Admin_QQUserService quser = new Admin_QQUserService();
            ViewBag.qqusers = quser.GetByQQUserNums();
            ViewBag.MetaKey = model.GetWebSiteInfo().MetaKey;
            ViewBag.SiteTitle = model.GetWebSiteInfo().SiteTitle;
            ViewBag.Address = model.GetWebSiteInfo().Address;
            ViewBag.Links = link.GetCount();

            ViewBag.ClassList = classService.GetTypeList().ToList();//获取文章or标签分类
            ViewBag.DingList = article.GetDingArticle(3);//获取置顶文章
            ViewBag.HotList = article.GetHotArticle(5);//获取热门文章
            ViewBag.UserList = article.GetByQQUserList(12);//获取来访用户信息（默认QQ）

            //博客每页显示数目
            int PageSize = 5;
            ViewBag.PageSize = PageSize;
            //总条数
            int Count = article.GetByQQUserNum();
            ViewBag.Count = Count;

            //总页数
            int PageCount = (Count + PageSize - 1) / PageSize;
            ViewBag.PageCount = PageCount;

            //文章分类Id
            ViewBag.ClassId = ArticleID;
            return View();
        }

        /// <summary>
        /// 文章详情 视图
        /// </summary>
        /// <param name="Id"></param>
        /// <returns></returns>
        public ActionResult Detail(string DPOR369E0zc)
        {
            //参数加密
            var ArticleID = DPOR369E0zc == null ? 0 :  Convert.ToInt32(Des.DesDecrypt("guo", DPOR369E0zc));
            if (ArticleID > 0)
            {
                WebSiteInfo siteInfo = new WebSiteInfo();
                //获取节点key值
                ViewBag.Site = siteInfo.GetWebSiteInfo();
                //增加浏览次数
                var add = article.GetViewAdd(ArticleID);
                //获取文章详情数据
                var model = article.GetArticleInfo(ArticleID).FirstOrDefault();

                //延伸阅读
                ViewBag.OtherList = article.GetRandomArticleList(2);
                //每页显示数目
                int PageSize = 10;
                ViewBag.PageSize = PageSize;

                //总条数
                int Count = 0;
                if (ArticleID == 0)
                { Count = 0; }
                else
                { Count = article.GetComment(ArticleID); }
                ViewBag.Count = Count;
                //总页数
                int PageCount = (Count + PageSize - 1) / PageSize;
                ViewBag.PageCount = PageCount;

                return View(model);
            }
            else
            {
                throw new Exception("请返回上层页面重试！");
            }

        }

        /// <summary>
        /// 文章分页查询
        /// </summary>
        /// <param name="classId"></param>
        /// <param name="page"></param>
        /// <param name="pagesize"></param>
        /// <returns></returns>
        [HttpPost]
        public ContentResult LoadArticleByClass(int classId, int page, int pagesize)
        {
            string result = article.GetListByClassId(classId, page, pagesize);
            return Content(result);
        }

        /// <summary>
        /// 文章搜索
        /// </summary>
        /// <param name="context"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult SearchResult(string context)
        {
            var result = article.GetArticleListBySearch(context);
            return Json(result);
        }

        /// <summary>
        /// 加载评论
        /// </summary>
        /// <param name="context"></param>
        /// <returns></returns>
        [HttpPost]
        public ContentResult LoadArticleComment(int articleId, int page, int pagesize)
        {
            string result = article.GetFlowArticleComment(articleId, page, pagesize);
            return Content(result);
        }
    }
}

Blog1.0/Controllers/FeedbackController.cs
using Blog1._0.Data;
using Blog1._0.Service;
using System;
using System.Web.Mvc;
using Until;
using System.Linq;


namespace Blog1._0.Controllers
{
    /// <summary>
    /// 【留言】控制器
    /// </summary>
    public class FeedbackController : Controller
    {
        FeedbackService service = new FeedbackService();
        /// <summary>
        /// 留言首页视图
        /// </summary>
        /// <returns></returns> 
        public ActionResult Index()
        {
            WebSiteInfo siteInfo = new WebSiteInfo();
            ViewBag.Site = siteInfo.GetWebSiteInfo();
            int Count = service.GetFeedList();
            ViewBag.Count = Count;
            int PageSize = 10;
            ViewBag.PageSize = PageSize;
            ViewBag.PageCount = (Count + PageSize - 1) / PageSize;
            return View();
        }

        /// <summary>
        /// 加载留言数据
        /// </summary>
        /// <param name="page"></param>
        /// <param name="pagesize"></param>
        /// <returns></returns>
        [HttpPost]
        public ContentResult LoadFeedback(int page, int pagesize)
        {
            string result = service.GetFlowFeedback(page, pagesize);
            return Content(result);
        }

        /// <summary>
        /// 提交评论
        /// </summary>
        /// <param name="openid"></param>
        /// <param name="editorContent"></param>
        /// <param name="fromcity"></param>
        /// <param name="browserName"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateInput(false)]
        public JsonResult AddFeedback(string openid, string editorContent, string fromcity, string browserName)
        {
            var db = new Repository().Base();
            QQUserService services = new QQUserService();
            var userModel = services.GetQQUserInfo(openid).FirstOrDefault();
            if (userModel == null)
            {
                return Json(new AjaxResult { state = ResultType.error.ToString(), message = "非法提交，Openid不存在" });
            }
            if (!userModel.Status.Value)
            {
                return Json(new AjaxResult { state = ResultType.error.ToString(), message = "QQ用户已被锁定，无法留言" });
            }
            WebSiteInfo siteInfo = new WebSiteInfo();
            int maxFeedbackNum = Convert.ToInt32(siteInfo.GetWebSiteInfo().MaxFeedbackNum);//查询最大留言数量
            int todayFeedbackNum = service.GetTodayFeedbackNum(openid);//获取用户今日留言数量
            if (todayFeedbackNum >= maxFeedbackNum)//不能超过最大数量
            {
                //锁定QQ用户
                userModel.Status = false;
                db.Update(userModel);
                db.Commit();
                return Json(new AjaxResult { state = ResultType.error.ToString(), message = "留言提交失败，已超出每日最大提交数量" });
            }
            FeedbackModel model = new FeedbackModel()
            {
                SendId = userModel.Id,
                AcceptId = 0,
                Content = XSS.FilterXSS(editorContent),
                ParentId = 0,
                City = fromcity,
                Equip = browserName,
                CreateOn = DateTime.Now
            };
            bool result = service.CreateModel(model);
            if (result)
            {
                return Json(new AjaxResult { state = ResultType.success.ToString(), message = "留言提交成功" });
            }
            else
            {
                return Json(new AjaxResult { state = ResultType.error.ToString(), message = "留言提交失败" });
            }
        }

        /// <summary>
        /// 回复留言
        /// </summary>
        /// <param name="openid"></param>
        /// <param name="remarkId"></param>
        /// <param name="targetUserId"></param>
        /// <param name="editorContent"></param>
        /// <param name="fromcity"></param>
        /// <param name="browserName"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateInput(false)]
        public JsonResult ReplyFeedback(string openid, string remarkId, string targetUserId, string editorContent, string fromcity, string browserName)
        {
            var db = new Repository().Base();
            QQUserService services = new QQUserService();
            var userModel = services.GetQQUserInfo(openid).FirstOrDefault();//查询用户是否存在
            if (userModel == null)
            {
                return Json(new AjaxResult { state = ResultType.error.ToString(), message = "非法提交，Openid不存在" });
            }
            if (!userModel.Status.Value)
            {
                return Json(new AjaxResult { state = ResultType.error.ToString(), message = "QQ用户已被锁定，无法留言" });
            }
            WebSiteInfo siteInfo = new WebSiteInfo();
            int maxFeedbackNum = Convert.ToInt32(siteInfo.GetWebSiteInfo().MaxFeedbackNum);
            int todayFeedbackNum = service.GetTodayFeedbackNum(openid);
            if (todayFeedbackNum >= maxFeedbackNum)
            {
                //锁定QQ用户
                userModel.Status = false;
                db.Update(userModel);
                db.Commit();
                return Json(new AjaxResult { state = ResultType.error.ToString(), message = "留言提交失败，已超出每日最大提交数量" });
            }
            FeedbackModel model = new FeedbackModel()
            {
                SendId = userModel.Id,
                AcceptId = Convert.ToInt32(targetUserId),
                Content = XSS.FilterXSS(editorContent),
                ParentId = Convert.ToInt32(remarkId),
                City = fromcity,
                Equip = browserName,
                CreateOn = DateTime.Now
            };
            bool result = service.CreateModel(model);
            if (result)
            {
                return Json(new AjaxResult { state = ResultType.success.ToString(), message = "留言回复成功" });
            }
            else
            {
                return Json(new AjaxResult { state = ResultType.error.ToString(), message = "留言回复失败" });
            }
        }


    }
}

Blog1.0/Controllers/HomeController.cs
using Blog1._0.Service;
using System.Web.Mvc;
using Until;

namespace Blog1._0.Controllers
{
    /// <summary>
    /// 【首页】控制器
    /// </summary>
    public class HomeController : Controller
    {
        WebSiteInfo model = new WebSiteInfo();

        /// <summary>
        /// 首页视图
        /// </summary>
        /// <returns></returns> 
        public ActionResult Index()
        {
            ArticleService article = new ArticleService();
            ViewBag.HotArtileList = article.GetHotArticle(3);//热门文章
            return View(model.GetWebSiteInfo());
        }

        /// <summary>
        /// META标签描述 引用
        /// </summary>
        /// <returns></returns>
        public ActionResult Meta()
        {
            ViewBag.Site = model.GetWebSiteInfo();
            return PartialView("~/Views/Shared/_Meta.cshtml");
        }

        /// <summary>
        /// 【博客】头部 母版视图
        /// </summary>
        /// <returns></returns>
        public ActionResult Head()
        {
            ViewBag.Site = model.GetWebSiteInfo();
            return PartialView("~/Views/Shared/_Head.cshtml");
        }

        /// <summary>
        /// 【博客】尾部 母版视图
        /// </summary>
        /// <returns></returns>
        public ActionResult Foot()
        {
            ViewBag.Site = model.GetWebSiteInfo();
            return PartialView("/Views/Shared/_Foot.cshtml");
        }
    }
}

Blog1.0/Views/Home/Index.cshtml
@model Until.WebSiteModel
@using Until;
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="zh-Hans-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width" />
    <title>@Model.HomeTitle</title>
    <link rel="shortcut icon" type="~/Content/image/header_logo.png" href="~/Content/image/header_logo.png" />
    <meta name="keywords" content="@Model.MetaKey" />
    <meta name="description" content="@Model.MetaDescribe">
    <link href="~/Content/layui/css/layui.css" rel="stylesheet" type="text/css">
    <link href="~/Content/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="~/Content/css/index_style.css" rel="stylesheet" type="text/css">
    <link href="~/Content/css/animate.min.css" rel="stylesheet" type="text/css">
</head>
<body>
    <div id="menu" class="hover_animation menu_open" data-mark="false">
        <span></span>
        <span></span>
        <span></span>
    </div>
    <div id="navgation" class="navgation navgation_close">
        <ul class="point">
            <li><a href="@Url.Action("Index", "Home")">首页</a></li>
            <li><a href="@Url.Action("Index", "Article")">博客</a></li>
            <li><a href="@Url.Action("Index", "Feedback")">留言</a></li>
        </ul>
        <div class="logo"><a>@Model.SiteName</a></div>
    </div>
    <div class="section" id="section1">
        <div class="fp-tablecell">
            <div class="page1">
                <div class="nav wow zoomIn" data-wow-duration="2s">
                    <h1>@Model.SiteName</h1>
                    <p>@Model.SiteTitle</p>
                    <a class="layui-btn layui-btn-normal" style="margin-top: 20px" href="@Url.Action("Index", "Article")">Enter Blog</a>
                </div>
                <a class="next wow fadeInUp" data-wow-duration="2s" id="next"></a>
            </div>
        </div>
    </div>
    <div class="section" id="section2">
        <div class="fp-tablecell">
            <div class="page2">
                <div class="warp-box">
                    <div class="new-article">
                        <div class="inner wow fadeInDown" data-wow-delay=".2s">
                            <h1>热门文章</h1>
                            <p>
                                山有峰顶，海有彼岸，慢慢长途，<br />
                                终有回转，余味苦涩，终有回甘。 
                            </p>
                        </div>
                    </div>
                    <div class="layui-row">
                        @foreach (ArticleModel item in ViewBag.HotArtileList)
                        {
                            <div class="layui-col-xs12 layui-col-sm4 layui-col-md4  wow fadeInUp" style="padding: 0 10px">
                                <div class="single-news">
                                    <div class="news-head">
                                        <img src="@item.ImgUrl">
                                        <a href="/Article/Detail?DPOR369E0zc=@item.Test" class="link"><i class="fa fa-link"></i></a>
                                    </div>
                                    <div class="news-content">
                                        <h4>
                                            <a href="/">
                                                @item.ArticleTitle
                                            </a>
                                        </h4>
                                        <div class="date">
                                            @item.CRT_Time.ToString("yyyy年MM月dd日")
                                        </div>
                                        <p>
                                            @item.Abstract
                                        </p>
                                        <a href="/Article/Detail?DPOR369E0zc=@item.Test" class="btn">
                                            阅读更多
                                        </a>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="section" id="section3">
        <div class="fp-tablecell">
            <div class="page3">
                <div class="warp-box">
                    <div class="warp">
                        <div class="inner">
                            <div class="links">
                                <ul>
                                    <li class="wow fadeInLeft"><a href="/About">关于</a></li>
                                    <li class="wow fadeInRight"><a href="/Links">+友情链接</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="section" id="section4">
        <div class="fp-tablecell">
            <div class="page4">
                <div class="warp-box">
                    <div class="about">
                        <div class="inner">
                            <h1 class="wow fadeInLeft">来者是客</h1>
                            <p class="wow fadeInRight">
                                人的一生是万里山河，来往无数客，有人给山河添色，有人使日月无光，有人改他江流，有人塑他梁骨，大限到时，不过是立在山巅，江河回望。                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer class="footer wow fadeInUp" id="contact">
        <div class="footer-top">
            <div class="container">
                <div class="layui-row">
                    <div class="layui-col-xs12 layui-col-sm6 layui-col-md4">
                        <div class="single-widget about">
                            <div class="footer-logo">
                                <h2>@Model.SiteName</h2>
                            </div>
                            <p>@Model.SiteTitle</p>
                            <div class="button">
                                <a href="/About" class="btn layui-btn layui-btn-normal">About Me</a>
                            </div>
                        </div>
                    </div>
                    <div class="layui-col-xs12 layui-col-sm6 layui-col-md4">
                        <div class="single-widget">
                            <h2>相关链接</h2>
                            <ul class="social-icon">
                                <li class="active"><a href="/Article"><i class="fa fa-book"></i>博文</a></li>
                                <li class="active"><a href="/Feedback"><i class="fa fa-comments"></i>留言</a></li>
                                <li class="active"><a href="/Archives"><i class="fa fa-files-o"></i>归档</a></li>
                                <li class="active"><a href="/Diarys"><i class="fa fa-snowflake-o"></i>日记</a></li>
                                <li class="active"><a href="/Links"><i class="fa fa-hashtag"></i>友链</a></li>
                                <li class="active"><a href="/About"><i class="fa fa-share"></i>关于</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="layui-col-xs12 layui-col-sm12 layui-col-md4">
                        <div class="single-widget contact">
                            <h2>联系我</h2>
                            <ul class="list">
                                <li><i class="fa fa-map"></i>地址: @Model.Address</li>
                                <li><i class="fa fa-qq"></i>QQ: @Model.QQ </li>
                                <li><i class="fa fa-envelope"></i>邮箱: @Model.Mail</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="copyright">
            <div class="container">
                <div class="layui-row">
                    <div class="layui-col-xs12 layui-col-sm12 layui-col-md12 text-center">
                        <p>@Model.CopyRight&nbsp;<a href="https://beian.miit.gov.cn/" target="_blank" style="color:#bbb;">你的备案号</a></p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/Content/layui/layui.js"></script>
    <script src="~/Content/js/wow.min.js"></script>
    <script src="~/Content/js/index.js"></script>
    <!--百度站长平台链接索引的自动提交-->
    <!--每当用户访问这些页面时，就会通过这段脚本从百度下载一个1x1的gif，同时记录页面此时此刻的URL地址，然后推送给百度。-->  
    <script>
        //(function () {
        //    var bp = document.createElement('script');
        //    var curProtocol = window.location.protocol.split(':')[0];
        //    if (curProtocol === 'https') {
        //        bp.src = 'https://zz.bdstatic.com/linksubmit/push.js';
        //    }
        //    else {
        //        bp.src = 'http://push.zhanzhang.baidu.com/push.js';
        //    }
        //    var s = document.getElementsByTagName("script")[0];
        //    s.parentNode.insertBefore(bp, s);
        //})();

        (function () {
            var canonicalURL, curProtocol;
            //Get the <link> tag
            var x = document.getElementsByTagName("link");
            //Find the last canonical URL
            if (x.length > 0) {
                for (i = 0; i < x.length; i++) {
                    if (x[i].rel.toLowerCase() == 'canonical' && x[i].href) {
                        canonicalURL = x[i].href;
                    }
                }
            }
            //Get protocol
            if (!canonicalURL) {
                curProtocol = window.location.protocol.split(':')[0];
            }
            else {
                curProtocol = canonicalURL.split(':')[0];
            }
            //Get current URL if the canonical URL does not exist
            if (!canonicalURL) canonicalURL = window.location.href;
            //Assign script content. Replace current URL with the canonical URL
            !function () {
                var e = /([http|https]:\/\/[a-zA-Z0-9\_\.]+\.baidu\.com)/gi,
                    r = canonicalURL, t = document.referrer;
                if (!e.test(r)) {
                    var n = (String(curProtocol).toLowerCase() === 'https') ? "https://sp0.baidu.com/9_Q4simg2RQJ8t7jm9iCKT-xh_/s.gif" : "//api.share.baidu.com/s.gif";
                    t ? (n += "?r=" + encodeURIComponent(document.referrer), r && (n += "&l=" + r)) : r && (n += "?l=" + r); var i = new Image; i.src = n
                }
            }(window);
        })();
    </script>
    <script>
        //主页背景图
        layui.use(['jquery'], function () {
            var $ = layui.jquery;
            $("#section1").css("background-image", "url(@Model.Frontface)");
        })
    </script>
    <!--雪花效果-->
    <script src="~/Content/js/snow.js"></script>
    <!--飞舞樱花效果-->
    @*<script type="text/javascript" src="https://cdn.jsdelivr.net/gh/Ukenn2112/UkennWeb@3.0/index/web.js"></script>*@
</body>
</html>